name: Build and deploy react to gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      run: npm install
    - name: Build and Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token
      run: npm run deploy
